#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AlcoStoper.Resource", IsApplication=true)]

namespace AlcoStoper
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_down = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int horizontal_page_margin = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int margin_huge = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int margin_large = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int margin_medium = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int margin_small = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int margin_tiny = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int vertical_page_margin = 2131165185;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int beer = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int beer1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int beer2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int beerr = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int beerr1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int beerr2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int beery = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int beery1 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int beery2 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ButtonCreateStyle = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cocktail = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int cocktail1 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int cocktail2 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int cocktailr = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int cocktailr1 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int cocktailr2 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int cocktaily = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int cocktaily1 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int cocktaily2 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int edit_text_style = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int food = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int glass = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int glassr = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int glassy = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int happy = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int happy1 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_action_info = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_action_new = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_action_person = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_action_search = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Icon = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ProgressBarStyle = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int sad = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int shouting = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int tile = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int users = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int xs = 2130837541;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09002a
			public const int add = 2131296298;
			
			// aapt resource value: 0x7f09002c
			public const int addAlcohole = 2131296300;
			
			// aapt resource value: 0x7f09000b
			public const int alco1 = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int alco2 = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int alco3 = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int alco4 = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int alco5 = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int alco6 = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int alco7 = 2131296273;
			
			// aapt resource value: 0x7f090026
			public const int alcoholeName = 2131296294;
			
			// aapt resource value: 0x7f090027
			public const int alcoholePercent = 2131296295;
			
			// aapt resource value: 0x7f090021
			public const int btnCreateContact = 2131296289;
			
			// aapt resource value: 0x7f09002b
			public const int contacts = 2131296299;
			
			// aapt resource value: 0x7f090000
			public const int container = 2131296256;
			
			// aapt resource value: 0x7f09002d
			public const int delete = 2131296301;
			
			// aapt resource value: 0x7f090002
			public const int etNameAlcohole = 2131296258;
			
			// aapt resource value: 0x7f090019
			public const int happy = 2131296281;
			
			// aapt resource value: 0x7f09001b
			public const int happy1 = 2131296283;
			
			// aapt resource value: 0x7f09000a
			public const int horisontalScroll = 2131296266;
			
			// aapt resource value: 0x7f090025
			public const int imgAlcohole = 2131296293;
			
			// aapt resource value: 0x7f090028
			public const int imgPic = 2131296296;
			
			// aapt resource value: 0x7f090014
			public const int label = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int listViewAlcohole = 2131296277;
			
			// aapt resource value: 0x7f090024
			public const int listViewContacts = 2131296292;
			
			// aapt resource value: 0x7f090023
			public const int picture = 2131296291;
			
			// aapt resource value: 0x7f090006
			public const int radioGroup = 2131296262;
			
			// aapt resource value: 0x7f090008
			public const int rbRed = 2131296264;
			
			// aapt resource value: 0x7f090007
			public const int rbWhite = 2131296263;
			
			// aapt resource value: 0x7f090009
			public const int rbYellow = 2131296265;
			
			// aapt resource value: 0x7f090016
			public const int restart = 2131296278;
			
			// aapt resource value: 0x7f090012
			public const int resultImage = 2131296274;
			
			// aapt resource value: 0x7f090017
			public const int sad = 2131296279;
			
			// aapt resource value: 0x7f090013
			public const int save = 2131296275;
			
			// aapt resource value: 0x7f090004
			public const int sbPercent = 2131296260;
			
			// aapt resource value: 0x7f090029
			public const int search = 2131296297;
			
			// aapt resource value: 0x7f09001d
			public const int shouting = 2131296285;
			
			// aapt resource value: 0x7f090022
			public const int texture = 2131296290;
			
			// aapt resource value: 0x7f09001a
			public const int tvHappy = 2131296282;
			
			// aapt resource value: 0x7f09001c
			public const int tvHappy1 = 2131296284;
			
			// aapt resource value: 0x7f090001
			public const int tvNameAlcohole = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int tvPercent = 2131296259;
			
			// aapt resource value: 0x7f090005
			public const int tvPercentNumber = 2131296261;
			
			// aapt resource value: 0x7f090018
			public const int tvSad = 2131296280;
			
			// aapt resource value: 0x7f09001e
			public const int tvShouting = 2131296286;
			
			// aapt resource value: 0x7f09001f
			public const int txtName = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int txtNumber = 2131296288;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_camera = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int add_alcohole = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int alco_control = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int alco_level = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_sign_up = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int fragment_camera2_basic = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int row_alcohole = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int row_contact = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int actionbar = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int actionbar_alcohole = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int popup_menu = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int popup_menu_alcohole = 2131230723;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int ApplicationName = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int intro_message = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int picture = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int points = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060004
			public const int AppTheme = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int CustomActionBarTheme = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int MaterialTheme = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int MyActionBar = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int Theme_Base = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int Theme_Sample = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int Widget = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int Widget_SampleMessage = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int Widget_SampleMessageTile = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int dialog_animation = 2131099657;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
